# Generated by Django 4.0.6 on 2022-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_alter_placement_row_alter_placement_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='row',
            field=models.IntegerField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (2, 2), (6, 6)], verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='seat',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Место'),
        ),
    ]
